upd: cosmic-desktop, icewm

diff --git a/cosmic-desktop/packages/cosmic-desktop/postrm b/cosmic-desktop/packages/cosmic-desktop/postrm
--- a/cosmic-desktop/packages/cosmic-desktop/postrm
+++ b/cosmic-desktop/packages/cosmic-desktop/postrm
@@ -1,6 +1,6 @@
 #!/bin/sh -e
 
-if getent passwd cosmic-initial-setup >/dev/null && which deluser >/dev/null 2>&1; then
-    deluser --system cosmic-initial-setup || echo "Could not remove cosmic-initial-setup user."
+if getent passwd cosmic-initial-setup >/dev/null; then
+    userdel --system cosmic-initial-setup || echo "Could not remove cosmic-initial-setup user."
 fi
 exit 0
